name: animal_adoption
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  dio: ^5.4.1
  intl: ^0.18.0
  loader_overlay: ^4.0.0
  flutter_svg: 2.0.10+1
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  flutter_inappwebview: ^5.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  another_flushbar: ^1.12.30
  share_plus: ^7.2.2

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen: ^5.4.0
  hive_generator: ^2.0.1

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
    - family: PT Serif
      fonts:
        - asset: assets/font/PT_Serif-Web-Bold.ttf
          weight: 700
        - asset: assets/font/PT_Serif-Web-Regular.ttf
          weight: 400
    - family: Comfortaa
      fonts:
        - asset: assets/font/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/font/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/font/Comfortaa-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 400

  
